image: openjdk:16
stages:
- build
build:
  stage: build
  script:
    - |
      chmod +x ./gradlew
      ./gradlew build
      ls -l build
  artifacts:
    name: reports
    when: always
    paths:
      - build/reports